name: create_release
on:
  push:
    tags:
      - '*.*.*'

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Install cocogitto
        uses: actions-rs/install@v0.1
        with:
          crate: cocogitto
          version: latest

      - name: Generate changelog
        run: cog changelog --at ${{ steps.get_version.outputs.VERSION }} > ${{ github.workflow }}_changelog.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workflow }}_changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
